### ISSUE TITLE
High CPU usage running the basic window example

### ISSUE THREAD

**Issue by lluz55** [Not-Nik/raylib-zig#2]
Zig bindings:
![zig raylib cpu usage](https://user-images.githubusercontent.com/48956502/80867241-92c41480-8c69-11ea-8e27-cf44f8667346.png)

Go bindings:
![go raylib cpu usage](https://user-images.githubusercontent.com/48956502/80867406-38778380-8c6a-11ea-8228-1b3cdb65be34.png)

**Comment by Not-Nik** [comment]
Not quite sure where this comes from. I tried running the basic window example with both the plain C source and in Zig and they have about the same CPU usage. Also when you look at the binding all it really does is define extern functions, structs and enums so nothing that could really impact CPU usage.
<img width="292" alt="Screen Shot 2020-05-03 at 22 37 05" src="https://user-images.githubusercontent.com/32980656/80914472-26dbcc00-8d8f-11ea-8a2c-ca99ce075747.png">

**Comment by raysan5** [comment]
Check `raylib/src/config.h`, comment `SUPPORT_BUSY_WAIT_LOOP` and `SUPPORT_HALF_BUSY_WAIT_LOOP`

**Comment by lluz55** [comment]
> Also when you look at the binding all it really does is define extern functions, structs and enums so nothing that could really impact CPU usage.

I know. I just wanted to have some idea of ​​what could be doing this. I tested with Nim bindings and it shares similar result as in Go

**Comment by Not-Nik** [comment]
Closing this as the binding no longer depends on a pre-installed raylib version.

**Comment by rcorre** [comment]
FWIW, I encountered this on Linux raylib 3.7 zig 0.8. Commenting out `SUPPORT_HALF_BUSY_WAIT_LOOP` dropped the CPU to near-0.
