### ISSUE TITLE
disable exit key

### ISSUE THREAD

**Issue by pfgithub** [Not-Nik/raylib-zig#3]
Currently, this is required to disable the exit key:
```zig
ray.SetExitKey(@ptrCast(*const ray.KeyboardKey, &@as(c_int, 0)).*);
```
This would be nicer if the KeyboardKey enum was non-exhaustive, then it would be,
```zig
ray.SetExitKey(@enumToInt(ray.KeyboardKey, 0));
```
or if KeyboardKey had a null option,
```zig
ray.SetExitKey(.KEY_NULL);
```

**Comment by Not-Nik** [comment]
Yup, you're completely right. Thanks for the feedback, I'll get right to it.

**Comment by Not-Nik** [comment]
Should work now. Feel free to reopen if it doesn't

**Comment by Not-Nik** [comment]
PS: you mixed up `enumToInt` and `intToEnum`. The latter would have worked before this fix, but with raylib-zig I'm trying to avoid conversions as much as possible, to improve code readability.

**Comment by pfgithub** [comment]
`intToEnum` is what I meant, and that didn't work before the fix because the enum is exhaustive and 0 is not a valid option
